main: me.wobbychip.nogravityarmourstand.Main
name: NoGravityArmourStand
version: 1.0
author: WobbyChip

commands:
  NoGravityArmourStand:
    description: Disables armour stand gravity!
    usage: "Usage: /<command> [on | off | reload]"