main: me.wobbychip.repairwithxp.Main
name: RepairWithXP
version: 1.0
author: WobbyChip

commands:
  RepairWithXP:
    description: Allows you to use your xp to repair stuff!
    usage: "Usage: /<command> [on | off | reload | perTicks | perXP]"