main: me.wobbychip.custompotions.Main
name: CustomPotions
api-version: 1.17
version: 1.0
author: WobbyChip

commands:
  cpotions:
    description: Allows you to check custom potion
    usage: "Usage: /<command>"