main: me.wobbychip.ipbind.Main
name: IPBind
version: 1.0
author: WobbyChip

commands:
  ipbind:
    description: Allows you to bind your ip to your account.
    usage: "Usage: /<command> player"
  ipunbind:
    description: Allows you to unbind your ip from your account.
    usage: "Usage: /<command> player"