enableMessage: '&9[Whitelist] Whitelist has loaded!'
permissionMessage: '&cYou do not have permissions!'
reloadMessage: '&9Reloaded Whitelist.'
usageMessage: '&9Usage /wl [on | off | reload | add | remove | list]'
kickMessage: '&cYou are not whitelisted.%n Please contact with an administrator.'

saveMessage: '&9Saved config.'
listMessage: '&9Whitelisted players: %player_list%'
listEmpty: '&9Whitelist is empty.'

onMessage: '&9Whitelist is now on.'
alreadyOnMessage: '&9Whitelist is already on.'
offMessage: '&9Whitelist is now off.'
alreadyOffMessage: '&9Whitelist is already off.'
incorrectArgument: '&cIncorrect Argument!'

addedToWhitelist: '&9%player% has been added to whitelist.'
alreadyInWhitelist: '&9%player% is already added to whitelist.'
removedFromWhitelist: '&9%player% has been removed from whitelist.'
notInWhitelist: '&9%player% is not in whitelist.'

Enabled: false