enableMessage: '&9[PerPlayerKeepInventory] PerPlayerKeepInventory has loaded!'
permissionMessage: '&cYou do not have permissions!'
incorrectArgument: '&cIncorrect Argument!'
reloadMessage: '&9Reloaded PerPlayerKeepInventory.'
usageMessage: '&9Usage /PerPlayerKeepInventory [on | off | reload]'

onMessage: '&9PerPlayerKeepInventory is now on.'
alreadyOnMessage: '&9PerPlayerKeepInventory is already on.'
offMessage: '&9PerPlayerKeepInventory is now off.'
alreadyOffMessage: '&9PerPlayerKeepInventory is already off.'

Enabled: false