#Time in idk what format, with hand 0.2 = 1 second
destroyTime: 17280.0

#Should bedrock drop when broken
shouldDrop: true

#Enable timer in action bar with time left and percents
enableTimer: false

#What tools can be used to obtain bedrock
correctTools: ["NETHERITE_PICKAXE"]