# Time between crafts in ticks
craftCooldown: 8

# Configures if crafters can be disabled with redstone input
# 'direct' - crafter can be disabled only with direct powering from redstone dust/components
# 'indirect' - crafter can be disabled by powering a block next to it (doesn't allow quasi-connectivity to disable crafters)
redstoneMode: 'indirect'

# Configures whether hoppers/dispensers can move items in and out of crafter inventory
allowBlockRecipeModification: true