enableMessage: '&9[DiscordWhitelist] Discord whitelist has loaded!'
loginException: '&9[DiscordWhitelist] There was an error logging in!'
guildException: '&9[DiscordWhitelist] Could not find the guild!'
permissionMessage: '&cYou do not have permissions!'
reloadMessage: '&9Reloaded discord whitelist.'
usageMessage: '&9Usage /dwl [on | off | reload]'
kickMessage: '&cYou are not whitelisted.'
secondReason: '%nDiscord nickname and minecraft username should be same.%nAnd you need to have a community role.'

onMessage: '&9Discord whitelist is now on.'
alreadyOnMessage: '&9Discord whitelist is already on.'
offMessage: '&9Discord whitelist is now off.'
alreadyOffMessage: '&9Discord whitelist is already off.'
incorrectArgument: '&cIncorrect Argument!'

Enabled: false
Token: ''
GuildID: ''
RoleID: ''