main: me.wobbychip.discordwhitelist.Main
name: DiscordWhitelist
version: 1.0
author: WobbyChip

commands:
  dwl:
    description: Allows you to use whitelist with discord with role.
    usage: "Usage: /<command> [on | off | reload]"