main: me.wobbychip.entitylimit.Main
name: EntityLimit
version: 1.0
author: WobbyChip

commands:
  EntityLimit:
    description: Limit entity spawn!
    usage: "Usage: /<command> [on | off | reload | limit | distance]"